### ISSUE TITLE
EventTickets multiple auths

### ISSUE THREAD

**Issue by websymphony** [PlaceOS/google#10]
Hey @stakach,

Currently EventTickets relies on `auth` object to provide the `signing_key` to encode the jwt payload. 

https://github.com/PlaceOS/google/commit/7c395690461bc9e573aa84ff9db709b6ac84540f#diff-46afd85ce2fc4d64c6fd3531e632d221R156 

The change to use multiple auths doesn't have any impact on `wallet_api` because it provides an instance of `FileAuth`. 
But, if we were to use google shard on its own for generating google passes, with a different auth provider than `FileAuth`, it will throw error, since not all providers have `signing_key`. 

To support all auths, we'll need to update `EventTickets` to take `signing_key` as an input that it can use to encode, rather than rely on `auth` object to provide it.

**Comment by stakach** [comment]
Does this commit resolve the issue?
https://github.com/PlaceOS/google/commit/7c395690461bc9e573aa84ff9db709b6ac84540f

**Comment by stakach** [comment]
oh I see, the signing key is a separate field in the file auth. Thanks for pointing that out!
