### ISSUE TITLE
How to authenticate with Google in order to use translate cloud api

### ISSUE THREAD

**Issue by frojnd** [PlaceOS/google#11]
I was going through google translate docs where it says it's best to have client library and then I found this shard. In wiki you have example of how to authenticate. I downloaded that json file but I don't know how to load it since instructions says:
`Google::Auth.new(issuer: "test@example.com", signing_key: PRIVATE_KEY, scopes: "https://www.googleapis.com/auth/admin.directory.user.readonly", sub: "admin@example.com")`

What is issuer here? 
What is PRIVATE_KEY? Is this system ENV and I must extract PRIVATE_KEY from that .json file where I saw private key?
What is sub?

Sorry if I'm being too nubish. I am because I just registered for google cloud translate where it says to use it either with client or with oauth2. Any help appreciated.

**Comment by frojnd** [comment]
These are the keys inside project.json file:
```
[
  "auth_provider_x509_cert_url",
  "auth_uri",
  "client_email",
  "client_id",
  "client_x509_cert_url",
  "private_key",
  "private_key_id",
  "project_id",
  "token_uri",
  "type"
]
```

**Comment by stakach** [comment]
Yeah so there are two auth options in this shard you can use your `project.json` file directly:
```
auth = Google::FileAuth.new(file_path = "/absolute_path/project.json", scopes: "https://www.googleapis.com/auth/cloud-translation", sub: "your@gmail.account")

translate = Google::Translation.new(auth: auth)
translate.translate("Some text to translate", to: "de")
```

or you can extract the private_key from the file:

```
# where client email and private_key are extracted from the JSON file
auth = Google::Auth.new(issuer: client_email, signing_key: private_key, scopes: "https://www.googleapis.com/auth/cloud-translation", sub: "your@gmail.account")

translate = Google::Translation.new(auth: auth)
translate.translate("Some text to translate", to: "de")
```

**Comment by frojnd** [comment]
Thank you for your quick response. I guess I must go over your instructions again because of:
```
Unhandled exception: Unauthorized
{
  "error": "unauthorized_client",
  "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."
} (Google::Exception)
  from lib/google/src/google.cr:20:9 in 'raise_on_failure'
  from lib/google/src/auth/auth.cr:51:7 in 'get_token'
  from lib/google/src/auth/file_auth.cr:14:7 in 'get_token'
  from lib/google/src/translate/translate.cr:75:9 in 'get_token'
  from lib/google/src/translate/translate.cr:46:30 in 'translate:to'
  from src/translator.cr:7:1 in '__crystal_main'
  from ../../../../../usr/lib/crystal/crystal/main.cr:105:5 in 'main_user_code'
  from ../../../../../usr/lib/crystal/crystal/main.cr:91:7 in 'main'
  from ../../../../../usr/lib/crystal/crystal/main.cr:114:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

**Comment by stakach** [comment]
Yeah getting the permissions correct in google is a bit complicated
You need to add the scope `https://www.googleapis.com/auth/cloud-translation`

Our guide on how to do this is here:
https://docs.google.com/document/d/1JqyFG8VStwUH01EyR1mJVbrfJQOedm5tUMQCgyVsWbs/edit#heading=h.7zvhm4juor8q

**Comment by frojnd** [comment]
I wen through the docs. It appears I need to create admin account. In order to create admin I have to create G suite account. In order to create G suite account I have to have a registered domain. Was hoping I can authenticate without all that :D Or un other words make my existing gmail account work with translate api.

**Comment by Dan-Do** [comment]
When I Goto https://admin.google.com/
There is,
admin.google.com is used for Google Workspace accounts only. Regular Gmail accounts cannot be used to sign in to admin.google.com. Learn More
