### ISSUE TITLE
Google Translate Planned?

### ISSUE THREAD

**Issue by watzon** [PlaceOS/google#5]
Just wondering if Google Translate is planned for this. This library is looking awesome so far, but there's only one Translate API wrapper right now and it's 4 years old.

**Comment by stakach** [comment]
We're just implementing APIs we use on projects so it's more or less feature complete from our point of view.

Auth is typically the hardest thing with Google as their APIs are usually pretty straight forward (currently writing up a doc on how to configure g suite for use with this code - which I'll share in the readme soon)

Feel free to extend and we'll gladly accept contributions if you open a pull request

**Comment by stakach** [comment]
Added [this guide](https://docs.google.com/document/d/1JqyFG8VStwUH01EyR1mJVbrfJQOedm5tUMQCgyVsWbs/edit?usp=sharing) to the readme

**Comment by watzon** [comment]
Thanks for the quick response. I figured I may as well take a crack at adding this myself. It's based on the translate v2 API rather than v3 because I had no idea what's going on in the v3 docs regarding projects and such.

**Comment by stakach** [comment]
and it looks like v2 is not deprecated: https://cloud.google.com/translate/docs/reference/rest/v2/translate which is good
